### ISSUE TITLE
[SYSTEM] - While typing characters sometimes get reordered

### ISSUE THREAD

**Issue by kmack3** [dataspread/dataspread-web#104] opened 2017-09-14 18:04 UTC
ie if I type Kelly, it is shown as eKlly. It only happens with the first two characters, and yes I'm sure that I'm not just making a typo. it does not happen all of the time, but probably 50% of the time.

**Comment by Legandary23** [comment] 2017-09-15 21:28
I could not reproduce the issue, can you try it again?

**Comment by twattanawaroon** [comment] 2017-09-15 21:54
Just to confirm it happens to me too. It looks like there's a race between you activating a cell and some code setting the cursor to the beginning. It's more likely to occur if you type quickly, and after you've been doing something else and come back to data entry (like that function has left cache or something).

**Comment by twattanawaroon** [comment] 2018-12-20 21:12
(Hopefully) resolved by Virtualized Grid.

**Closed by twattanawaroon** 2018-12-20 21:12 UTC
Labels: bug, wont fix now
