### ISSUE TITLE
Error caused by clicking cell.

### ISSUE THREAD

**Issue by nbajiaoshi** [dataspread/dataspread-web#92] opened 2017-09-13 06:42 UTC
When I click on cell I would see this sometimes:"Destination range must include source range and can be fill in one direction only".
Don't remember the scenario.

**Comment by mangeshbendre** [comment] 2017-09-13 18:21
The issue is caused when selection change is not valid for auto fill.
Fixed in be591e6.

**Closed by mangeshbendre** 2017-09-13 18:21 UTC
