### ISSUE TITLE
[SYSTEM] All the cells with formula show an exception when opening a saved book

### ISSUE THREAD

**Issue by rahmansunny071** [dataspread/dataspread-web#120] opened 2017-09-18 14:52 UTC
Sample exception dump:

org.zkoss.zss.model.impl.FormulaResultCellValu�org.zkoss.poi.ss.formula.eval.RelTableEva�employe�dep�[[Lorg.zkoss.poi.ss.formula.eval.StringEval�Rhond�Eng�Le�Eng�org.zkoss.zss.model.impl.CellImpl$InnerCellValu��org.zkoss.zss.model.impl.sys.formula.FormulaEngineImpl$FormulaExpressionImplSQL("SELECT employee,dept FROM sr_try1 WHERE dept = 'Engr'"�[Lorg.zkoss.poi.ss.formula.ptg.Ptg�org.zkoss.poi.ss.formula.ptg.StringPt�SELECT employee,dept FROM sr_try1 WHERE dept = 'Engr�org.zkoss.poi.ss.formula.ptg.FuncVarPt�y  @

![image](https://user-images.githubusercontent.com/8811607/30548136-f2ed4d0a-9c56-11e7-955e-32a59f576b7a.png)

**Comment by twattanawaroon** [comment] 2017-09-18 22:51
looks like a duplicate of #112. Can you check if it's resolved?

**Comment by rahmansunny071** [comment] 2017-09-19 16:09
Tried again. This time the table related formula cells were showing the exception.

![image](https://user-images.githubusercontent.com/8811607/30602723-1299bf60-9d2b-11e7-8b10-fb52a09a241a.png)

**Closed** 2017-09-19 20:17 UTC
